spring:
  application:
    name: chat-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/pet_chat_dev?currentSchema=chat
    username: postgres
    password: 123456789
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
