name: CI

on:
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        strategy:
            matrix: 
                version: [21, 25, 26]
        uses: ivanbyone/pet-support-chat/.github/workflows/build.yml@develop
        with:
            java-version: ${{ matrix.version }}

    test:
        strategy:
            matrix: 
                groups: ['unit']
        uses: ivanbyone/pet-support-chat/.github/workflows/build.yml@feature/issue
        with:
            group: ${{ matrix.groups }}
